### ISSUE TITLE
Crashes AngularJS when used offline

### ISSUE THREAD

**Issue by endareceo** [dylanfprice/angular-gm#26]
I tried bundling this in a PhoneGap app, but offline the Google Maps library isn't available. This causes angular-gm to crash the entire angular application. 

Error: [$injector:unpr] Unknown provider: angulargmContainerProvider <- angulargmContainer
    at hasOwnPropertyFn (file:///Users/bram/Documents/Phonegap/bpost/www/lib/angularjs/angular.js:60:12)
    at file:///Users/bram/Documents/Phonegap/bpost/www/lib/angularjs/angular.js:2964:19
    at Object.getService [as get](file:///Users/bram/Documents/Phonegap/bpost/www/lib/angularjs/angular.js:3086:39)
    at file:///Users/bram/Documents/Phonegap/bpost/www/lib/angularjs/angular.js:2969:45
    at getService (file:///Users/bram/Documents/Phonegap/bpost/www/lib/angularjs/angular.js:3086:39)
    at invoke (file:///Users/bram/Documents/Phonegap/bpost/www/lib/angularjs/angular.js:3107:13)
    at Object.instantiate (file:///Users/bram/Documents/Phonegap/bpost/www/lib/angularjs/angular.js:3141:23)
    at $get (file:///Users/bram/Documents/Phonegap/bpost/www/lib/angularjs/angular.js:5554:28)
    at update (file:///Users/bram/Documents/Phonegap/bpost/www/lib/angularjs/angular-route.js:831:32)
    at Object.$get.Scope.$broadcast (file:///Users/bram/Documents/Phonegap/bpost/www/lib/angularjs/angular.js:10207:28)

**Comment by ffabreti** [comment]
@joe1chen, I'm using Ionic and offline is a mess when using angular-gm.
Thank you so much for sharing your code, will give it a try.
